### ISSUE TITLE
Third party syncing

### ISSUE THREAD

**Issue by Vilhelm-Ian** [Librum-Reader/Librum#1]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
ability to synch books with third party databases like nextcloud, or google drive

**Comment by Hukfbd** [comment]
I’m always frustrated when my boyfriend don’t let me take one more sip in
our Starbucks Frappuccino 😔

**Comment by JJTech0130** [comment]
I’m very confused. I’m assuming this issue is about integrating with WhisperSync and other providers, however, why didn’t you fill in the issue template? Also, what does that have to do with Frappuccinos?

**Comment by Creapermann** [comment]
@JJTech0130, book syncing will be added. The services I plan to integrate for now, are google drive, dropbox and nextcloud
