### ISSUE TITLE
[Feature Request] Flatfile annotation storage support

### ISSUE THREAD

**Issue by bugzy** [Librum-Reader/Librum#10]
**Is your feature request related to a problem? Please describe.**
Most annotation support in ereaders is cloud linked. This means that users have no access to their annotations without some kind of account on a dedicated cloud service (open or closed). It will be nice to have some kind of flat file support for annotations that can be accessed by users for several other purposes (i.e. colation of annotations form various books for research, sync using some other program of choice, conversion ito other formates, etc.)

**Describe the solution you'd like**
This is already possible and has been implemented by the foliate reader. See link below:
https://github.com/johnfactotum/foliate/wiki#how-are-notes-and-bookmarks-stored

**Describe alternatives you've considered**
If you adopt the specs/version implemented by there is the benefit of cross-compatibility

**Comment by Creapermann** [comment]
I understand this as being some kind of Download-Button, to download all notes for a book in a plain-text format format like json, is this correct? 
If so, this definitely sounds doable and seems like a nice feature, but for the close future the focus will remain on firstly getting notes to work well with the server.

I'll update this feature request when a final decision on this feature was made.

**Comment by bugzy** [comment]
Much thanks.

**Comment by DavidLazarescu** [comment]
We do not support notes yet. Once we will, I'll make sure that we have a flatfile download option. I will close this issue for now.
