### ISSUE TITLE
Mobile/Tablet App?

### ISSUE THREAD

**Issue by alirezaalavi87** [Librum-Reader/Librum#100]
Hi guys, great project.

It would be really great if we could develop a mobile/tablet app, since such app would be incomplete without an accompanying 
mobile app to continue your reading everywhere and even on android e-ink devices.

I suggest using Ionic+Vue for creating the mobile app as it will be truly free and more desirable to the FOSS minded audience of this platform (as opposed to flutter, or react native). And I would like to contribute to starting the project.

I would love if the maintainer(s) give their opinion on creating this app and what technologies we should use.

**Comment by DavidLazarescu** [comment]
Hey, we already started working on the mobile application (Android) of Librum. It is using Qt and C++, like the desktop application, since Qt is crossplatform and the core application is easily reusable on mobile OS'. Only the build issues need to be sorted out and the UI needs to be adapted.

**Comment by alirezaalavi87** [comment]
Ok that's great to hear! thanks.
