### ISSUE TITLE
Why username must contain first name and last name?

### ISSUE THREAD

**Issue by fernvenue** [Librum-Reader/Librum#110]
Hi, I just tried to register Librum, but I found out that I have to type first name and last name, I wondering why I must have first name and last name? There are so many cultral doesn't use first name or last name, please don't think everyone on the earth have first name and last name, and don't think that first name and last name means same in different cultral.

Some articles:

- [Your last name contains invalid characters](https://blog.jgc.org/2010/06/your-last-name-contains-invalid.html)
- [Some problems with 'first name' and 'last name' fields in data](https://utcc.utoronto.ca/~cks/space/blog/programming/WhyNotFirstAndLastNameFields)
- [程序员对人名的错误想法](https://medium.com/@askzy1/%E7%A8%8B%E5%BA%8F%E5%91%98%E5%AF%B9%E4%BA%BA%E5%90%8D%E7%9A%84%E9%94%99%E8%AF%AF%E6%83%B3%E6%B3%95-5f98ce5294d1)

**Comment by TravisLittlechilds** [comment]
I've only found Librum and haven't yet poked into the code, but I was pointed at this [W3C page on names](https://www.w3.org/International/questions/qa-personal-names). 

Just adding the link here since it's usually a decent best practices resource. When I get some free time I'll see if there's anything I can help with!

**Comment by DavidLazarescu** [comment]
In the next release (0.12.1) First Name and Last Name will be removed  and unified into one "Name" field. 

Thanks for the feedback!

**Comment by fernvenue** [comment]
Thank you sooo much for this change, I didn't expect that actually, but this finally happened. Thanks again for this, I really appreciate it :)

**Comment by DavidLazarescu** [comment]
I'm always happy to improve Librum where ever I can! Thanks again for pointing out the issue, if you run into anything else, feel free to create another issue.
