### ISSUE TITLE
BibTeX/BibLaTeX support

### ISSUE THREAD

**Issue by alfureu** [Librum-Reader/Librum#113]
**Is your feature request related to a problem? Please describe.**
I would like to get a BibTeX/BibLaTeX support for reference management

**Describe the solution you'd like**
In books details there should be an option to generate BibTeX/BibLaTeX records for reference managers. An absolute best would be if Librum would be able to collect/generate these via ISBN data

**Describe alternatives you've considered**
N/A

**Additional context**
I would love to use Librum for long-term (!!!) self-hosted book/document preservation with notes, highlights, mainly for research purposes

**Comment by DavidLazarescu** [comment]
This sounds like a nice idea, but requires a lot of work and is pretty niche atm, so we will not work on it very soon. I have noted it and once we got some time we'll look into it.

Contributions on this are, of course, also more than welcome.
