### ISSUE TITLE
iOS App

### ISSUE THREAD

**Issue by URBANsUNITED** [Librum-Reader/Librum#114]
Hi!

I saw that you've accounced an iOS app.
As I can sign my apps by myself, is there a posibility to get my hands on that app already?
If not, when do you think you'll release it?

Thanks

URBANsUNITED

**Comment by DavidLazarescu** [comment]
Hey, we are currently still working on the Android version which will still take some time. Once we finish that we will start working on the IOS port of Librum. I haven't tried building it on IOS yet. I suppose it won't work out of the box so it sadly isn't possible to use Librum on IOS already.
