### ISSUE TITLE
Some books can't be deleted

### ISSUE THREAD

**Issue by ArtDoctor** [Librum-Reader/Librum#117]
**Describe the bug**
When I remove a book from my library, and then restart the app, the book is still in my library. I also can't download it, and when I try to sync after deleting the book, it doesn't help.
My cloud storage is 0.1GB, it shouldn't be full.

**To Reproduce**
I am not sure if this error is reproducible, I don't remember how I added these bugged books. But even if I delete the app and then download and install it again, it still doesn't work.

**Expected behavior**
When I delete the book, it doesn't appear anymore.

**Screenshots**
1,2,3 - before app restart
<img width="373" alt="Screenshot_1" src="https://github.com/Librum-Reader/Librum/assets/46786959/06c01882-bb40-4f91-bcc0-28723db26daa">
<img width="398" alt="Screenshot_2" src="https://github.com/Librum-Reader/Librum/assets/46786959/bce29323-5557-4d0c-8585-95c90682fc16">
<img width="245" alt="Screenshot_3" src="https://github.com/Librum-Reader/Librum/assets/46786959/7d272a1d-135b-4f20-96fa-f3e4162e14f2">
4 - after app restart
<img width="384" alt="Screenshot_4" src="https://github.com/Librum-Reader/Librum/assets/46786959/7786d108-386b-4dcc-8624-c04cad9b3ca2">

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 22H2 22621.2861
**Additional context**

**Comment by DavidLazarescu** [comment]
Thanks for reporting. I suppose that this is a problem on the server side, thus it would be very useful if you could send me the email you used for your Librum account or figure out the book uuid via the application logs.

**Comment by ArtDoctor** [comment]
Of course, here it is: artdoctorka@gmail.com

**Comment by DavidLazarescu** [comment]
hm, it also is quite weird that all of your books are marked as not-uploaded. Please also send me the application logs which are stored at: C:/Users/<USER>/AppData/Roaming/Librum-Reader/Librum/librum_log.txt

**Comment by DavidLazarescu** [comment]
Also, does this problem occur with every book, or is there one specific book that you can't delete?

**Comment by ArtDoctor** [comment]
[librum_log.txt](https://github.com/Librum-Reader/Librum/files/13873823/librum_log.txt)
Here is the log file. 
Some books are fine, I was able to upload them, do stuff, and then delete them without any problems. But some are broken (and usually the broken books are copies of the correct books that I was able to download/delete). For example in the screenshots above you can see "LAL CTU" 2 times, even though I uploaded it only once.

**Comment by DavidLazarescu** [comment]
I see, can you try deleting the folder at C:/Users//AppData/Roaming/Librum-Reader/Librum/local_libraries and restart the app to see if everything works correctly after that?

**Comment by ArtDoctor** [comment]
Yes, it works perfectly fine, thank you! All the broken books disappeared.

**Comment by DavidLazarescu** [comment]
Glad to hear that. I apologize for the trouble.
