### ISSUE TITLE
Perpetual "Your book has not been uploaded to the cloud"

### ISSUE THREAD

**Issue by joeyism** [Librum-Reader/Librum#119]
**Describe the bug**
Sometimes when I upload pdfs, it gives me the warning that "Your book has not been uploaded to the cloud". I've tried restarting Librum, my computer, delete and re-add the books, etc.

(Thank you for the hard work, despite this bug, I'm really enjoying Librum and I think you guys are doing a great job)

**To Reproduce**
I'm not quite sure if it's reproducible, since it happens pretty randomly

**Expected behavior**
I expected either the pdfs to be uploaded automatically, a retry to upload button, or logs to indicate why uploading has failed.

**Screenshots**
<img width="1823" alt="Screenshot 2024-01-12 at 11 56 07" src="https://github.com/Librum-Reader/Librum/assets/7503144/7d55f34f-44d1-44c8-99be-9d28a673af23">

**Desktop (please complete the following information):**
 - OS: MacOS 
 - Version Sonoma 14.1.2

**Comment by DavidLazarescu** [comment]
Hey, thanks for reporting the issue. Is your online storage full by any chance (To check that, go to Settings->Storage)?

**Comment by joeyism** [comment]
> Hey, thanks for reporting the issue. Is your online storage full by any chance (To check that, go to Settings->Storage)?

Hey thanks for the reply.

<img width="1610" alt="Screenshot 2024-01-12 at 15 17 33" src="https://github.com/Librum-Reader/Librum/assets/7503144/76803932-3023-4839-a6cc-b60773180b5f">

It doesn't seem like my online storage is full

**Comment by DavidLazarescu** [comment]
I see, thanks. It would be very useful if you could provide the email that you are using for your Librum account so that I can check for unusual behavior on the server side.

**Comment by joeyism** [comment]
> I see, thanks. It would be very useful if you could provide the email that you are using for your Librum account so that I can check for unusual behavior on the server side.

joeyism101@gmail.com

Is it also possible to view the logs on my end? i.e. what about the upload is causing it to fail

**Comment by DavidLazarescu** [comment]
Thanks. Yes, on linux you can find the logs in ~/.local/share/Librum-Reader/Librum/librum_log.txt, I am not sure about mac, but you can search for a file called "librum_log.txt"

**Comment by joeyism** [comment]
> Thanks. Yes, on linux you can find the logs in ~/.local/share/Librum-Reader/Librum/librum_log.txt, I am not sure about mac, but you can search for a file called "librum_log.txt"

Okay, I found one of the reasons why. When I look in the logs (which on macOS is `~/Library/Application Support/Librum-Reader/Librum`), I got the error
```
Getting User failed (401): Host requires authentication
```
so I manually logged out and logged back in, which solved a few of the upload issues.

I also get the error
```
"Tracking book failed. Failed opening .libmeta file at: $SOMEPATH/local_libraries/9163841211685437495/09b86f0c-8694-48e1-b97c-2a0bcb0c22a1.libmeta"
```
even though that file does exist and there doesn't seem to be any bugs with the JSON. I've attached the pdf file for reference.
[2019-mapl-tillet-kung-cox.pdf](https://github.com/Librum-Reader/Librum/files/13921007/2019-mapl-tillet-kung-cox.pdf)

**Comment by DavidLazarescu** [comment]
Thanks, this information is very helpful. I have seen the 401 errors multiple times now, this definitely is a bug. I'll look for what exactly causes it.

**Comment by DavidLazarescu** [comment]
I suppose that the issue could be due to an expiring JWT token. It is currently set to expire after 2 months. I suppose you did not log into your account again in the last 2 months from the machine that you are experiencing issues with? This definitely is a bug and I'll fix it now.

**Comment by Airiswindy** [comment]
Sorry but has this been fixed? I am still getting this error

**Comment by DavidLazarescu** [comment]
Hey, this wasnt fixes yet. Try to log in and out of your account and see if that helps

**Comment by Airiswindy** [comment]
idk if logging out and back in helped but i also uploaded some new books to check if they sync and they did after a delay, some of my old books still have the sync error so idk but seems to be workable for now ty
