### ISSUE TITLE
Change / increase scroll speed?

### ISSUE THREAD

**Issue by copypasteonly** [Librum-Reader/Librum#123]
**Is your feature request related to a problem? Please describe.**
It's really been bugging me how the scroll speed is too slow to my liking, increasing it 50% faster or just having the option of changing the scroll speed would be great!

**Describe the solution you'd like**
I would like to have the option to change the scroll speed.

**Describe alternatives you've considered**
A workaround that I do is I zoom out a bit in order to have more of the page scroll by which can sometimes be unnecessary.

**Additional context**
N/A

**Comment by DavidLazarescu** [comment]
Thanks for the feedback. I have written it down and we'll add an option for that soon.
