### ISSUE TITLE
Display size

### ISSUE THREAD

**Issue by Codingkingsman** [Librum-Reader/Librum#135]
Good day to you sir,
I'm raising this request for the windows size of the application
can there be an option like other software to remember the previous window size and position?
because it gets a bit difficult to resize the window always to the size that I usually prefer
The software usually boots in full screen, and on pressing the resize button , it literally shrinks to a very small square
I hope you'll look into this request
Thanking you in advance!

**Comment by DavidLazarescu** [comment]
This is definitely doable, I have noted it and I'll add it in a future release. Thanks for pointing that out!
