### ISSUE TITLE
Struggling to build reader on MAC

### ISSUE THREAD

**Issue by MrMxyzptlk** [Librum-Reader/Librum#136]
I have the latest Intel mini with the latest MAC OS and have all the prereqs / configs setup.

This is during the build step...
a docker of the client would make all of this complexity for non-devs such as myself; go away.

Thank you...

Exception: Command failed: . venv-mupdfwrap-3.11-x64/bin/activate && python -m pip install --upgrade pip && python -m pip install --upgrade libclang swig && python ./scripts/mupdfwrap.py -d build/shared-release -b -j 0 m01 && deactivate
make[2]: *** [src/application/CMakeFiles/mupdf] Error 1
make[1]: *** [src/application/CMakeFiles/mupdf.dir/all] Error 2
make: *** [all] Error 2

**Comment by DavidLazarescu** [comment]
Can you send me all of the build output? This is not enough to spot the error.

**Comment by MrMxyzptlk** [comment]
That's all of the build output...

**Comment by karrysg** [comment]
I have just successfully built Librum on my MacBook after encountering similar issues. The issue was which components of Qt I was installing. My problem was solved by installing the QT Creator app and the main framework. I used QT 6.6.2. I'm not a developer myself, but this may be the issue. Let me know.

**Comment by MrMxyzptlk** [comment]
Thanks for the tip; I added ALL components of QT and am now getting these errors when I run cmake.

CMake Warning:
  No source or binary directory provided.  Both will be assumed to be the
  same as the current working directory, but note that this warning will
  become a fatal error in future CMake releases.


CMake Error at CMakeLists.txt:72 (add_subdirectory):
  add_subdirectory given source "libs/rapidfuzz-cpp" which is not an existing
  directory.


CMake Error at CMakeLists.txt:76 (add_subdirectory):
  add_subdirectory given source "src/" which is not an existing directory.


-- Configuring incomplete, errors occurred!

**Comment by karrysg** [comment]
Hi you might need to rerun the setup script again. cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=Off -DCMAKE_PREFIX_PATH=/Users/(your username)/Qt/6.6.2/macos .. only thing I can think of. I deleted everything in my build-Release directory and started over.

**Comment by MrMxyzptlk** [comment]
OK, started over I'm not on the cmake --install step and here is the output.

anthony@Mini-Driver Librum % cmake --install
Usage: cmake --install <dir> [options]
Options:
  <dir>              = Project binary directory to install.
  --config <cfg>     = For multi-configuration tools, choose <cfg>.
  --component <comp> = Component-based install. Only install <comp>.
  --default-directory-permissions <permission>
     Default install permission. Use default permission <permission>.
  --prefix <prefix>  = The installation prefix CMAKE_INSTALL_PREFIX.
  --strip            = Performing install/strip.
  -v --verbose       = Enable verbose output.

**Comment by DavidLazarescu** [comment]
> Thanks for the tip; I added ALL components of QT and am now getting these errors when I run cmake.
> 
> CMake Warning: No source or binary directory provided. Both will be assumed to be the same as the current working directory, but note that this warning will become a fatal error in future CMake releases.
> 
> CMake Error at CMakeLists.txt:72 (add_subdirectory): add_subdirectory given source "libs/rapidfuzz-cpp" which is not an existing directory.
> 
> CMake Error at CMakeLists.txt:76 (add_subdirectory): add_subdirectory given source "src/" which is not an existing directory.
> 
> -- Configuring incomplete, errors occurred!

This means that you haven't cloned the repo correctly. Make sure to use `--recursive` in the git clone command

**Comment by DavidLazarescu** [comment]
> OK, started over I'm on the cmake --install step and here is the output.
> 
> anthony@Mini-Driver Librum % cmake --install Usage: cmake --install
> 
> [options]
> Options:
> = Project binary directory to install. --config = For multi-configuration tools, choose . --component = Component-based install. Only install . --default-directory-permissions Default install permission. Use default permission . --prefix = The installation prefix CMAKE_INSTALL_PREFIX. --strip = Performing install/strip. -v --verbose = Enable verbose output.

I think this might be an issue from in the docs. Try `cmake --install .` (with the . at the end)

**Comment by MrMxyzptlk** [comment]
I also get this when I run step 4. The only way I've gotten past 4. is to not cd into build-Release.

anthony@Mini-Driver build-Release % cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=Off -DCMAKE_PREFIX_PATH=/Users/anthony/Qt/6.6.2/macos
CMake Warning:
  No source or binary directory provided.  Both will be assumed to be the
  same as the current working directory, but note that this warning will
  become a fatal error in future CMake releases.


CMake Error: The source directory "/Users/anthony/Documents/Librum/build-Release" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.

**Comment by DavidLazarescu** [comment]
> I also get this when I run step 4. The only way I've gotten past 4. is to not cd into build-Release. This is after deleting the Librum directory and cloning recursively; which I've done each time.
> 
> anthony@Mini-Driver build-Release % cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=Off -DCMAKE_PREFIX_PATH=/Users/anthony/Qt/6.6.2/macos CMake Warning: No source or binary directory provided. Both will be assumed to be the same as the current working directory, but note that this warning will become a fatal error in future CMake releases.
> 
> CMake Error: The source directory "/Users/anthony/Documents/Librum/build-Release" does not appear to contain CMakeLists.txt. Specify --help for usage, or press the help button on the CMake GUI.

You forgot the `..` in step 4. Try to copy the exact command: `cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=Off -DCMAKE_PREFIX_PATH=<path/to/Qt> ..` and it should work.

**Comment by MrMxyzptlk** [comment]
Rookie error! I've been removing the 2 dots everytime...
Thanks.

**Comment by DavidLazarescu** [comment]
Glad to hear that the build works now!

**Comment by MrMxyzptlk** [comment]
Yep, in this case I kept the . at the end of the line, and it was not needed.
After I exported the DYLD...path without the . I was able to run Librum.
