### ISSUE TITLE
A question about 'active'

### ISSUE THREAD

**Issue by 1250890838** [Librum-Reader/Librum#137]
hello,on 
[https://github.com/Librum-Reader/Librum/blob/main/src/presentation/modules/CustomComponents/buttons/MButton.qml](url) 
I found the **active** custom attribute,I don't quite understand what it means. Generally speaking, it should refer to the interval between when the mouse is pressed and when it is released.but on
 [https://github.com/LibrumReader/Librum/blob/main/src/presentation/modules/CustomComponents/MConfirmAccountDeletionPopup.qml](url)
i found that it doesn't seem to be the case,because the **active** attribute does not change when pressed.
Can you please tell me its specific meaning?thanks in advance.

**Comment by DavidLazarescu** [comment]
Hey, thanks for pointing that out. `active` is indeed supposed to be `true` when the button is selected, it seems like I forgot it there. We will be changing that behavior soon anyways to a more intuitive way of handling the focus though.
