### ISSUE TITLE
"Open with" any book outside Librum

### ISSUE THREAD

**Issue by nedfreetoplay** [Librum-Reader/Librum#141]
**Is your feature request related to a problem? Please describe.**
I often download books as files and want to "Open with" and get an open Librum with an open book.
By analogy with notepad, when I have configured to open txt files in notepad, I do not have to open notepad and then open the file in it. The file is opened automatically.

**Describe the solution you'd like**
I want Librum to open automatically when I open a book and add it to my library and open it on the first page.

**Describe alternatives you've considered**
Well, I have to open Librum first, then open explorer and transfer the book I need to the library.

**Additional context**
I'm done.

**Comment by DavidLazarescu** [comment]
This definitely is planned. I have written it on my to-do list and will hopefully get some time to implement it for one of the next releases.

**Comment by DavidLazarescu** [comment]
Added this feature in #15aaa634ea886a800aeee9dd5304eb65d5d5b8c0
