### ISSUE TITLE
about presentation qml files export library on windows

### ISSUE THREAD

**Issue by 1250890838** [Librum-Reader/Librum#143]
hello,can i ask a question here?

In `presentation` file, there are many qml files. When compiling `presentation` project on Windows, dll and lib file will all be generated，that are all right.However, I wrote a demo myself that only qml files within a qrc file to generate library  but only dll file were generated, without lib files,so in my application can not refere to qml path. Can you tell me the reason?

**Comment by 1250890838** [comment]
my expression may not be clear. this is the same problem as me https://forum.qt.io/topic/26995/solved-make-shared-library-with-qml-files/6

**Comment by DavidLazarescu** [comment]
I sadly don't have much experience with this for windows and can't understand the error without seeing the source code. I'd recommend you to ask this question in the Qt discord server: https://discord.gg/p2nMmZK5
