### ISSUE TITLE
Neither bug or feature: Location of Librum.conf on Macos for Librum client.

### ISSUE THREAD

**Issue by MrMxyzptlk** [Librum-Reader/Librum#144]
I've done a find on the entire Mac HDD and have been unable to locate the Librum.conf.
Would you kindly let me know where it resides, or if I need to create it from scratch.

I have already run the client and have been in the GUI.

Thank you.

**Comment by kerryandjane** [comment]
I haven't figured it out completely just yet BUT i feel like i'm close.
`/System/Volumes/Data/Users/{your username}/Library/Preferences/com.librumreader.Librum.plist`

After adjusting the file nothing changes. Even changing the theme to light does nothing here. 🤷 

let me know if you get it working please.

**Comment by DavidLazarescu** [comment]
I will close this for now since we will soon support MacOS officially, which should resolve all the issues.
