### ISSUE TITLE
[Feature Request] Go back to the folder where you opened the book after you closed it

### ISSUE THREAD

**Issue by westtle** [Librum-Reader/Librum#147]
I like the new folder system but I find it annoying that whenever I open a book from a folder and close the book it brings me to the "All Books" section on the home page.

![The issue.](https://westt.s-ul.eu/cNDzMrPb "The Issue")

It would be nice if when you close a book it brings you back to the folder you opened that book from (and maybe even keep the sidebar open).

**Comment by DavidLazarescu** [comment]
This should add the requested improvement. I did not change it to re-open the sidebar since it felt a bit off to auto open the sidebar every time you go back.
