### ISSUE TITLE
[Feature Request] Ability to view list of the highlights I have made in my book. Also, ability to take notes.

### ISSUE THREAD

**Issue by AShaaban0109** [Librum-Reader/Librum#150]
**Is your feature request related to a problem? Please describe.**
No way to view the highlights I have made in my book. Also, no way to take notes.

**Describe the solution you'd like**
I would love to be able to see all the highlights I have made in one book all listed together as is the case for bookmarks. This can also allow filtering by colors of highlights which I can give an arbituary name (eg. memorable quotes in yellow, funny quotes in red, etc.).  And when I want to browse through the memorable quotes I have selected for a certain book, I can easily see them, and go to their page by clicking on them. 

Also, if I for example want to take notes on a certain passage or section that I have highlighted and find important, having the ability to store these notes would be very useful. Maybe this is deviating a little from the main direction the app wants to take, but it's just a personal preference for me.

**Comment by DavidLazarescu** [comment]
Hey, listing highlights is on our list. Our current focus is on the mobile applications though, but we'll get to it asap.

Also, adding an extensive note-taking system is planned as well, but will take some time too since its quite a big feature.
