### ISSUE TITLE
Add Bengali translation

### ISSUE THREAD

**Issue by rago666** [Librum-Reader/Librum#151]
My first time translating, so let me know if something is wrong.
[librum_bn.zip](https://github.com/Librum-Reader/Librum/files/14545532/librum_bn.zip)

**Comment by DavidLazarescu** [comment]
Thanks for adding the translation! It will be in the next release.

**Comment by DavidLazarescu** [comment]
Hey @rago666, I have the bengali translation in this commit: 35d7fe1c3915fd3647597828b2399fbaa9715414

We have made changes that are not yet in that file.  It would be great if you could download https://github.com/Librum-Reader/Librum/blob/dev/develop/src/presentation/translations/librum_bg.ts, fill out the few new words and create a PR with the new file.
