### ISSUE TITLE
Reading page zoom does not match default zoom set in configurations

### ISSUE THREAD

**Issue by brunoqueiroz1984** [Librum-Reader/Librum#158]
The default zoom is set to 150%. When I enter a book, the zoom is correct, but when I click to change it, the dropdown is focused on 100%, and attempting to change from 150% to 100% fails at first click, since the dropdown is already focused on 100%. Clicking on it a second time changes the zoom to 100%

1. Make sure your default zoom is 150%
2. Open Librum and then open any book
3. Click on the zoom, you should see that actually 100% is focused
4. Try changing to 100% by clicking on it, it should do nothing on first click

**Expected behavior**

**Screenshots**
![image](https://github.com/Librum-Reader/Librum/assets/18530421/04ebd059-9266-4235-889d-4a7fe24fb3f3)
At first when the dropdown is opened

![image](https://github.com/Librum-Reader/Librum/assets/18530421/8a0b07de-555b-476f-95eb-fd0556c12cca)
When 100% is cliked the first time

 - OS: Windows 11
 - Version 0.12.1

**Comment by DavidLazarescu** [comment]
Thanks for the report. I was about to release 0.12.2, but I'm gonna quickly fix this and squeeze it in too.

**Comment by DavidLazarescu** [comment]
This should fix it, let me know if it now works as expected for you.
