### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by vikramwalia** [Librum-Reader/Librum#162]
**Is your feature request related to a problem? Please describe.**
Need support for a docker based deployment.

**Describe the solution you'd like**
If we could get a docker-compose file to deploy everything.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by DavidLazarescu** [comment]
A docker image of the server already exists. Check the Selfhosting section and follow the link to Librum-Server

**Comment by astappiev** [comment]
What about the docker image for the frontend?
I wanted to try this alternative to kavita, but I'm not going to deploy the frontend manually.
