### ISSUE TITLE
Feature Request: Adding a root folder for all your books that is synchronized with the app. 

### ISSUE THREAD

**Issue by futuremotiondev** [Librum-Reader/Librum#168]
**Is your feature request related to a problem? Please describe.**
It would be a wonderful feature for Librum to support adding a root folder where all your e-books are stored, and have the application either auto-sync on launch, or manually sync when you want to update the library.

**Describe the solution you'd like**
An option to add a synced folder that contains all your e-books. Librum would then scan this directory recursively and automatically add new books either on startup or a manually initiated sync.

See screenshot below.

**Describe alternatives you've considered**
None

**Additional context**

![ApplicationFrameHost_gRDpXRWELY](https://github.com/Librum-Reader/Librum/assets/33441569/d1b77295-520e-4152-9834-8526cd9fa184)

**Comment by DavidLazarescu** [comment]
Thanks for the proposal. We are planning to add a tool to recursively import folders into your Library and optionally create in-app folders to organize them as they were organized in the original file system.

Basing on and rescanning a directory could be a bit more complicated though and interfere with server side syncing. 

I'll write it down and see if we can add something like that.
