### ISSUE TITLE
Can this software be used without logging in?

### ISSUE THREAD

**Issue by 1250890838** [Librum-Reader/Librum#171]
as the title says

**Comment by DavidLazarescu** [comment]
It can not. You can self-host the server, but even there you need to create an account. The whole idea of Librum is automatic syncing of books, your progress, highlights, bookmarks, ... Which all depends on having an account on the server.

**Comment by 1250890838** [comment]
In this case, I found a bug where you can switch pages with shortcut keys on the login page.for example,enter "Ctrl+2" can switch to home page without logging in.i will create a pull request soon.

**Comment by DavidLazarescu** [comment]
Thanks for the PR, it will be in the next version of Librum.
