### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by ted1958** [Librum-Reader/Librum#174]
Hi,
I found librum by searching a simple free efficient ebook reader. Tada.
So, I translated it in french, this is my little contribution. 

[librum_fr.zip](https://github.com/Librum-Reader/Librum/files/15139550/librum_fr.zip)

**Comment by DavidLazarescu** [comment]
Thank you, this will be in the next version of Librum!

**Comment by DavidLazarescu** [comment]
I added the french translation to dev/develop #f86afee42c7fc5fea81e8aef881cd7705e88b82d

I added you as the co-author by your name, since I do not have your email. If you want me to add your email as well, please share it.
