### ISSUE TITLE
Search feature in Home page

### ISSUE THREAD

**Issue by lngoctam** [Librum-Reader/Librum#177]
**Describe the bug**
The search function in the user library is not returned as expected. Instead of just returning the searched books only, it returns the searched book first, then followed by the rest of the books. This behavior may cause confusion and annoyance for users who expect a clear result.

**To Reproduce**
1. Go to 'Home'
2. Click on 'magnifying glass icon'
3. Type keyword:” years”
4. See result

**Expected behavior**
Only books containing the keyword “years” should be returned, as can be seen in the search feature of the "Free books" section.

**Screenshots**
An issue when searching in user library
![issue link 1](https://github.com/Librum-Reader/Librum/assets/58675059/03e56b78-a3a1-4a28-ba62-4b7c71673522)

Expected behavior in Free books section
![issue link 2](https://github.com/Librum-Reader/Librum/assets/58675059/41ffbfa3-90b8-4305-a7e6-a1dd0061597c)

**Desktop (please complete the following information):**
 - OS: Windows 11

**Comment by DavidLazarescu** [comment]
Hi, thanks for the feedback, but this behavior is intended. It is a fuzzy search and should sort your library by their similarity to the text you search for.

**Comment by lngoctam** [comment]
Should this behavior remain as it is, or should it be adjusted to function similarly to the search feature in the Free Books section?

**Comment by DavidLazarescu** [comment]
It is supposed to be that way and will stay this way for now, but I'll look into adding other possibilities for this in the future.
