### ISSUE TITLE
Vietnamese translation

### ISSUE THREAD

**Issue by lngoctam** [Librum-Reader/Librum#179]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Translation into Vietnamese  

**Describe alternatives you've considered**
I'm trying to get it done.

**Additional context**
No

**Comment by lngoctam** [comment]
[librum_vi.zip](https://github.com/user-attachments/files/15535511/librum_vi.zip)
Do you need anything other than librum_vi.ts file?

**Comment by DavidLazarescu** [comment]
No, that's all I Need. I'll add it to The Next Version. Thanks for The contribution!

**Comment by DavidLazarescu** [comment]
I have added the translation af78de1272e50bdbb5e8ead909c60bda0db16fed. I have mentioned you as the co author, since I do not have your email, I only added your name. If you want to be mentioned by your email as well, please share it.
