### ISSUE TITLE
~/.config/Librum-Reader/Librum.conf not being generated

### ISSUE THREAD

**Issue by Redmauss** [Librum-Reader/Librum#181]
**Describe the bug**
For self-hosting instructions when launching the app for first time via flatpak I have no Librum folders generated in my users `.config` directory.   I cannot then proceed with the step:

>  (Linux) Editing ~/.config/Librum-Reader/Librum.conf and setting selfHosted=true and serverHost to your server's url (e.g. serverHost=https://127.0.0.1:5001)

 - OS: "22.04.4 LTS (Jammy Jellyfish)"

**Additional context**
I setup the server no problems, haven't really been able to test it yet as I can't login via the client as the settings to change are not there, would it be possible to create this folder and file in my config directory?  I don't have an example config, so I haven't been able to do this yet. 

Please let me know, thank you.

**Comment by e-duMaurier** [comment]
@Redmauss 
If it helps, I found mine at
/home/$USER/.var/app/com.librumreader.librum/config/Librum-Reader
