### ISSUE TITLE
Make it easier to use self-hosted servers

### ISSUE THREAD

**Issue by parasiteoflife** [Librum-Reader/Librum#182]
**Is your feature request related to a problem? Please describe.**
For Windows is expected for the end-user to edit registry keys, at least for Linux you edit a config file.

**Describe the solution you'd like**
None of them are user friendly. Please add an option at app first start to either use your cloud servers or a self-hosted server and let us enter the server address there instead of requiring the end user to edit files or registry keys.

**Comment by DavidLazarescu** [comment]
> `snap install Librum` I'd love to see this.

This is planned, but the Qt version in the debian repo isn't the version Librum needs, so its not possible for us to publish it as deb or snap package yet. Once Qt 6.6 is in the debian repository, I will add it.

**Comment by DavidLazarescu** [comment]
> **Is your feature request related to a problem? Please describe.** For Windows is expected for the end-user to edit registry keys, at least for Linux you edit a config file.
> 
> **Describe the solution you'd like** None of them are user friendly. Please add an option at app first start to either use your cloud servers or a self-hosted server and let us enter the server address there instead of requiring the end user to edit files or registry keys.

This is definitely possible and I put it onto our to-do list!
