### ISSUE TITLE
Ability to change epub font. 

### ISSUE THREAD

**Issue by rago666** [Librum-Reader/Librum#29]
**Is your feature request related to a problem? Please describe.**
I find it harder to read book in some fonts, maybe I am dyslexic. So I use Lexend from google fonts which helps a lot. It would help a lot.

**Describe the solution you'd like**
Ability to change epub font.

**Comment by DavidLazarescu** [comment]
That's definitely something that we will support soon! We are focusing on some other basic features for now though, but its on our to-do list.

**Comment by DavidLazarescu** [comment]
Merging this issue with #167
