### ISSUE TITLE
[Feature Request] Stream books from existing calibre-web library

### ISSUE THREAD

**Issue by mparashis1** [Librum-Reader/Librum#3]
I would like to be able to stream my books the to the app from my calibre-web library on an external server. Other e-readers seem to allow network library's but end up just being a link that opens the calibre-web web page where i have to log in to download the book. I think being able to browse my servers bookshelf from inside the app and a single click to open and start reading would be a great feature.

The reason I would be requesting this is because I find calbre-web to be a pretty poor ereader, but it's a wonderful library and organizing tool. The strengths of a good eReader with the convenience of access to external libraries would make this the ultimate eReader app in my opinion.

I understand books are mostly small and easy to download but I would love to be able to set up my non tech savvy family up with an app that would be like "the netflix of books" for people with ebook libraries.

**Comment by Creapermann** [comment]
Librum is made for library management, thus calibre-web shouldnt be a necessity anymore. Non the less, we don't want to force anyone using Librums library, thus there will be multiple ways to sync external libraries with Librum, including Dropbox and google-drive. Syncing from custom servers is something we have in mind, but are not yet sure if it will be implemented.

This request will be updated, as soon as the decision is final.

**Comment by Audiosutras** [comment]
Follow up question? Is there a REST API endpoint for adding books to your library? Is there a directory I could add books to and Librum will add the book to the local and remote libraries?

**Comment by DavidLazarescu** [comment]
The server and client is opensource, thus you can access all the endpoints manually as well at api.librumreader.com.

What would be your usecase for this though?

**Comment by Audiosutras** [comment]
For `https://api.librumread.com` I'm receiving a `404` error code. 

Instead of using `+ add books` and selecting a book through the GUI to upload. It would be nice if you could perform a POST request or cli command to perform this action.

**Comment by DavidLazarescu** [comment]
You have written the domain wrongly. It's https://librumreader.com

**Comment by Audiosutras** [comment]
I understand that. Thanks for the response. Is `api.librumreader.com` a subdomain? Could you point me towards the docs for `api.librumreader.com`

**Comment by DavidLazarescu** [comment]
There is no documentation for the api endpoints since it's an internal api and it wasn't planned to be used by other applications. It is opensource though, so you can find all the endpoints in the src/infrastructure/data/endpoints.hpp and see what they expect and how they behave in the source code of the server.

We might very well add a terminal CI for librum in the future, but for now we are focusing on the GUI.

**Comment by Audiosutras** [comment]
Thanks for letting me know. Full steam ahead
