### ISSUE TITLE
Dictionary & translation support

### ISSUE THREAD

**Issue by rago666** [Librum-Reader/Librum#30]
**Is your feature request related to a problem? Please describe.**
When reading a book in second language it is kind of tedious to search the internet for certain word you don't understand. It also takes away focus from reading.

**Describe the solution you'd like**
Some way to search for word definition and translating word to different language. [Foliate](https://github.com/johnfactotum/foliate) has this feature.

Thank you! Have a good day.

**Comment by DavidLazarescu** [comment]
Thank you for the request. 
This is something that we will be implementing very soon. We have planned to add AI sentence explanation and summarizing as well.

**Comment by rago666** [comment]
That's amazing.
