### ISSUE TITLE
Cannot install on windows 11 23H2

### ISSUE THREAD

**Issue by LoneWolf993** [Librum-Reader/Librum#31]
**Describe the bug**
The setup does not run. Double clicking it, right clicking and running as admin, both do nothing. No error pops up, absolutely nothing happens.

**To Reproduce**
1. Download Librum Windows installer from the website.
2. Double click the setup or right click and run as admin.
3. Nothing happens.

**Expected behavior**
Expected the installer wizard to open up.

**Screenshots**
[Video](https://github.com/Librum-Reader/Librum/assets/66156681/7ab5c15c-b542-4893-bedf-3f7b98a8fabd)

**Desktop (please complete the following information):**
 - OS: Microsoft windows 11
 - Version: 23H3 (OS Build 22631.2265)

**Comment by DavidLazarescu** [comment]
Hi, thanks for reporting the issue.

I haven't heard about this of problem before. Could you please try to run the installer via the terminal and tell me if you get any output from it?

**Comment by LoneWolf993** [comment]
> Hi, thanks for reporting the issue.
> 
> I haven't heard about this of problem before. Could you please try to run the installer via the terminal and tell me if you get any output from it?

How can I run the installer via terminal?

**Comment by DavidLazarescu** [comment]
You should be able to right click in the folder where the installer is located and click on "Open in Terminal" and then just run `./librum-windows-0.7.0-installer.exe`

**Comment by LoneWolf993** [comment]
> ./librum-windows-0.7.0-installer.exe

thanks, running with terminal really did work
