### ISSUE TITLE
Integration with Ryot

### ISSUE THREAD

**Issue by IgnisDa** [Librum-Reader/Librum#33]
Hello I am the author of [Ryot](https://github.com/IgnisDa/ryot). I believe the goals of Librum and Ryot align wonderfully and would like to propose an intgeration between the two. What do you think about it?

**Describe the solution you'd like**
A webhook architecture in Librum that would inform Ryot when progress is made on a book.

Thank you for Librum, it is really useful for me!

**Comment by DavidLazarescu** [comment]
Hey, thank you for reaching out. I am generally open to these kind of integrations, but I'd need to know more about your project.

How exactly would Ryot work together with Librum?

**Comment by IgnisDa** [comment]
Ryot is meant for tracking media (in this case books). Every time you read a book, Librum will send your progress to Ryot so that it can be tracked.

**Comment by DavidLazarescu** [comment]
Does this mean that you are adding webhooks to multiple applications (e.g. e-book readers / library managers) so that they sync their data with you? If that's the case, what other services is Ryot connected with?

**Comment by IgnisDa** [comment]
Ryot supports a lot of services: https://ignisda.github.io/ryot/integrations.html.

**Comment by DavidLazarescu** [comment]
> Ryot supports a lot of services: https://ignisda.github.io/ryot/integrations.html.

I see. How exactly would the integration work?

**Comment by IgnisDa** [comment]
Does Librum have access to a book identifier? Ideally I would prefer that Librum sends the openlibrary or google books ID but I think this would be outside the project scope. In that case, an ISBN13 would work fine.

When I read a book, Librum will send a progress update event to the Ryot API"

```jsonc
{
  "isbn13": "<identifier>",
  "progress": 56.45, // progress out of 100%
}
```

Does this make sense?

**Comment by DavidLazarescu** [comment]
Librum parses the book files from the user's PC and thus doesn't have access to any of ISBNs. If you'd need the ISBN, I'd need to use some kind of ISBN database and try to find the proper ISBN for every book the user imports into the application.

**Comment by IgnisDa** [comment]
I'm not that familiar with how ebooks work but i thought their ISBN was attached to their file metadata?

**Comment by DavidLazarescu** [comment]
I have talked to the developers of the library that Librum uses for rendering the books and extracting their metadata and they say their Library does not support extracting ISBNs

**Comment by IgnisDa** [comment]
Well we can use the book title themselves but that's prone to errors.

**Comment by DavidLazarescu** [comment]
From what I know there are databases that you can use to get the ISBN of a book by its title. We might be able to use that.

**Comment by IgnisDa** [comment]
https://isbndb.com/ is paid.

**Comment by DavidLazarescu** [comment]
Yes, I suppose that this is not an option for now but if Librum gets more donations I could add that

**Comment by DavidLazarescu** [comment]
@IgnisDa I have been looking into the google books api which looks quite promising to get more book metadata (including the isbn). I didn't manage to find out if it is free for commercial use, or if it would cost as well though. I am waiting for a response from google's sales department and if it is free or cheap, I'd be able to integrate it soon.

**Comment by IgnisDa** [comment]
@DavidLazarescu it's free. I'm not aware how it would apply to Librum given its license. And yes using Google Books api would be great since Ryot already has support for it.

**Comment by DavidLazarescu** [comment]
I couldn't find where exactly it says that. Do you have a link to that doc?

**Comment by IgnisDa** [comment]
https://developers.google.com/books/docs/v1/using

**Comment by DavidLazarescu** [comment]
I have looked through this document before, but searching for "free", "price", "cost" and similar gave me no results. Could you be more specific on where exactly it says that it is free?

**Comment by IgnisDa** [comment]
I assume that the absence of such clauses means it is free for non-commercial uses.

**Comment by DavidLazarescu** [comment]
Librum is a commercial application though, this is why I wanted to make sure that I am not breaking any of their rules.

**Comment by IgnisDa** [comment]
Yep, then your approach to contacting them is the right way to proceed. Do let me know what they reply.

**Comment by DavidLazarescu** [comment]
I didn't get a reply and I can't seem to find further information on this, so I'll close this for now. I'll reach out once I know more.
