### ISSUE TITLE
Flagged as malicous by windows defender

### ISSUE THREAD

**Issue by yaamas** [Librum-Reader/Librum#35]
**Describe the bug**
Flagged as malicous by windows defender. This is my personal computer, so no GPO's or or anything.

**To Reproduce**
1. Go to '[https://librumreader.com/](https://librumreader.com/)'
2. Click on 'Download'
3. See error

**Expected behavior**
Download.

**Screenshots**
![image](https://github.com/Librum-Reader/Librum/assets/22547069/6b0194f7-7826-48c4-b20f-26af6827e957)

![image](https://github.com/Librum-Reader/Librum/assets/22547069/8119d5db-c1ce-4a21-a12b-6a8743c0df6e)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10.0.22621.2134

**Additional context**
N/A

**Comment by DavidLazarescu** [comment]
Hey, thanks for the issue report. I found some steps in the microsoft docs to avoid this, Ill work on this soon.

**Comment by DavidLazarescu** [comment]
The installer is now signed, so it shouldn't big flagged by the browser as malicious anymore.
It might still get flagged by microsoft defender when trying to execute it though. I have issued a submission for a review, so hopefully that shouldn't happen anymore either soon.
