### ISSUE TITLE
Librum not showing in i3wm

### ISSUE THREAD

**Issue by solankybasant** [Librum-Reader/Librum#36]
Is this application not for i3wm?

**Comment by DavidLazarescu** [comment]
I have never tried i3wm, but from what I read its a window manager on top of X11, so I see no reason why it shouldn't work.

What exactly do you mean with "not showing"?

**Comment by solankybasant** [comment]
When I am searching or try to open from the terminal itself output is command not found...but the same can be found in ubuntu. Why this is so

**Comment by DavidLazarescu** [comment]
How did you install Librum?

**Comment by solankybasant** [comment]
Using flatpak

**Comment by DavidLazarescu** [comment]
Ok, and you tried running it via: `flatpak run com.librumreader.librum`?

**Comment by DavidLazarescu** [comment]
Flatpak installs the .desktop files to a location in your home directory since it's not a system wide install. From my experience ubuntu needs to be restarted for it to show up in the menu.
