### ISSUE TITLE
Can't start Windows 11 Pro

### ISSUE THREAD

**Issue by logitechf** [Librum-Reader/Librum#37]
I downloaded the exe from the site, installed it, but the application does not want to start, no errors or something like that. And yes, I read a similar bug report, although there is something related to the installation, but mine is with the launch.

**Comment by DavidLazarescu** [comment]
Hi, could you please go to the installation directory (by default  C:\Program Files\Librum) and try to run librum.exe from the terminal and see if you get any errors printed out?

**Comment by logitechf** [comment]
> Hi, could you please go to the installation directory (by default C:\Program Files\Librum) and try to run librum.exe from the terminal and see if you get any errors printed out?

Sorry I didn't install Qt, visual studio 2019 and Cmake so it didn't start. In any case, thanks for the quick response!

**Comment by logitechf** [comment]
I installed Visual Studio 2019, Cmake and Qt and ran it successfully.

**Comment by DavidLazarescu** [comment]
@logitechf You should not need these dependencies when installing  Librum via the installer that you downloaded from the Website.

Did you build it from source or did you install it from https://librumreader.com?
