### ISSUE TITLE
Confirmation message not received

### ISSUE THREAD

**Issue by LoricAndre** [Librum-Reader/Librum#38]
**Describe the bug**
After trying to setup an account twice, I didn't receive any confirmation emails and my email address is not recognized by librum.

**To Reproduce**
1. Go to https://librumreader.com/
2. Click on Login, the Register
3. Create an account
4. The confirmation email popup appears
5. No email is received even after 24h

**Expected behavior**
The confirmation email is sent to my inbox

**Additional context**
I am using firefox, tried it on windows and linux.
I am using SimpleLogin for email aliases, and the mail never got to SimpleLogin so it is not my spam filter.

**Comment by DavidLazarescu** [comment]
Hey thanks for your message. We had some issues with the website registration and thought we have fixed it yesterday, but it apparently still doesn't work.
Please create an account via the application and not the website, that should work.

**Comment by LoricAndre** [comment]
It worked, thanks
