### ISSUE TITLE
Flagged as malicious by VirusTotal (probably false-positive)

### ISSUE THREAD

**Issue by Zen341** [Librum-Reader/Librum#39]
**Describe the bug**
One of VirusTotal vendors (Trapmine) flagged the Windows installer as malicious 

**To Reproduce**
1. Go to virustotal.com
2. Upload the Windows installer (version 0.7.0)
3. See the flag

You can go to https://www.virustotal.com/gui/file/97344eb191c152a4470e0c4fb300c434ff6ff23eae8099293c56094fad561e2f/ to see it directly

**Expected behavior**
No flags raised

**Screenshots**
![image](https://github.com/Librum-Reader/Librum/assets/79434568/b861ad1e-a445-42d2-a861-7327083cb1a6)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 0.7.0

**Additional context**
This is probably not a major issue, I just wanted to make awareness of this phenomenon

**Comment by DavidLazarescu** [comment]
Hey, thank you for reporting the issue. From what I see this false-positive is triggered because the file is not signed. This is not a major issue and does not mean that the program is malicious in any way. We will make sure to sign it in the future.

**Comment by DavidLazarescu** [comment]
Fixed it: https://www.virustotal.com/gui/file/225bf15b5b1adbb31a6f8d77fc7325ac034e29377d288df311c55dba7de0a74f?nocache=1
