### ISSUE TITLE
Add support for book export with annotations

### ISSUE THREAD

**Issue by PJansky** [Librum-Reader/Librum#42]
As someone who recently tried to immigrate from Kindle and discovered how difficult it is to export "your own" books, especially with annotations, it would be nice to have the peace of mind going into your app, that you as a user have the ability to easily export your books with all annotations. Obviously limitations apply, like there is no standard for storing epub annotations and highlights, but just being able to get the text/json/whatever document with all that stuff would be great benefit.
Keep up the great work!

**Comment by DavidLazarescu** [comment]
Hey, thanks for the recommendation. Exporting books with Librum is very easy, simply right click on it and you get an option to do so.

The annotations will also be exportable in a flat-file format. Check #10 for that.
