### ISSUE TITLE
Unresponsive options checkboxes in reader mode

### ISSUE THREAD

**Issue by malagem** [Librum-Reader/Librum#49]
Once in a book, in read mode (ie with the pages of the book displayed on screen), the options "Continuous pages" and "Display vertically" are totally unresponsive and cannot be clicked or actioned. I'm running version 0.8.0 on Windows 10.0.19045.3448.

![image](https://github.com/Librum-Reader/Librum/assets/6984657/dfe6bc9c-a74e-4c8a-ab3a-a7750cf86d08)

Since there are no settings in the global parameters to override these, it'd be nice if this could be fixed in a future release.

**Comment by DavidLazarescu** [comment]
These options are not yet implemented and are thus blocked. Once we will implement them in the future, we will unblock them and make these functionalities available.
