### ISSUE TITLE
Library Genesis

### ISSUE THREAD

**Issue by sha5672** [Librum-Reader/Librum#5]
**Is your feature request related to a problem? Please describe.**
One major feature that Calibre has is the ability to scrape sites such as Library Genesis and download the books for you.
**Describe the solution you'd like**
A built in tool that could search Libgen for books and automatically download them

**Comment by Creapermann** [comment]
As far as I know, services like libgen and z-lib are not legal, thus I don't plan to provide access to them in through application. I am not sure how calibre handles the legal aspect, but I wouldn't want to take the risk.

What you use to download books, if legal or not, is your choice. Librum will provide an easy import of any book.
