### ISSUE TITLE
Support DJVU file format

### ISSUE THREAD

**Issue by 82dev** [Librum-Reader/Librum#54]
**Is your feature request related to a problem? Please describe.**
Not a problem, but I have some books in DJVU I would like to add to my library

**Describe the solution you'd like**
Add support for the DJVU file format

**Describe alternatives you've considered**
I use Okular to read DJVU documents currently

**Comment by DavidLazarescu** [comment]
We have DJVU support in mind, but since the library we use to extract information from books does not support, we'd need to manually add support for it which takes some time.
