### ISSUE TITLE
No way of sending a confirmation mail after the prompt is closed

### ISSUE THREAD

**Issue by YosypC** [Librum-Reader/Librum#56]
**Describe the bug**
After #55 I tried closing the program. I can't login (not confirmed) nor sign up (already existing). Changing PW didn't help.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 22621.2283

**Comment by DavidLazarescu** [comment]
Hey, it's weird that you didn't get a email. What host are you using? We had a report of a similar error with selfhosted emails that are being redirected before. Would you mind providing the part after the '@' in your email?

**Comment by YosypC** [comment]
> Hey, it's weird that you didn't get a email.

I did. Dumbass me clicked "resend" 1ms after the confirmation box appeared and broke everything. I tried following the mail link nontheless but it prompts me with "There was a problem (...) We weren't able to confirm your account. Please register again, or contact us for support."

**Comment by DavidLazarescu** [comment]
Hm that is weird, I suppose not getting the email the first time means that resending it won't have an effect either tbh.

If you don't want to share your email here, you can send me an email at: help@librumreader.com with your email and I can check what's wrong.

**Comment by YosypC** [comment]
> Hm that is weird, I suppose not getting the email the first time[..]

I did get it. It arrived correctly a couple seconds after the signup, but I had clicked the resend button already. The resend button has never worked.

I'll contact you by mail.

**Comment by DavidLazarescu** [comment]
Ah ok, and the email link you clicked then didnt work?

**Comment by YosypC** [comment]
Correct. It showed me the error message I quoted a couple of messages ago, prompting me to register again.
