### ISSUE TITLE
Appimage release

### ISSUE THREAD

**Issue by chromer030** [Librum-Reader/Librum#60]
**Is your feature request related to a problem? Please describe.**
Yes, the heavy process of compiling the software.

**Describe the solution you'd like**
Please provide an appimage.
I'm aware of flatpak but appimage is portable and far more lighter in size.

**Describe alternatives you've considered**

**Additional context**

**Comment by DavidLazarescu** [comment]
We'll add AppImages at some point. I didn't have the time to learn about creating them yet, so I'll add it once I got more time to do some research on them.

Contributions would be greatly appreciated.

**Comment by DavidLazarescu** [comment]
Quick update, we are currently working on workflows to automate the release of app images and .tar.gz files in #61. As I mentioned there, the packaging tool for linux seems to have a bug which is currently holding us back, so I'll first need to resolve this.
I'll close this thread and we'll continue on #61.
