### ISSUE TITLE
Touch screen support

### ISSUE THREAD

**Issue by YosypC** [Librum-Reader/Librum#66]
Using the touch screen with fingers makes it a selection instead of pan. Also using a Stylus.

**Desktop (please complete the following information):**
 - OS: Windows 11 on Microsoft Surface Pro 8
 - Version 22H2

**Comment by DavidLazarescu** [comment]
Hey, we haven't payed much attention to touch yet. We were planning to improve that once we start working on the mobile version of Librum.

Are you able to flick up and down by swiping next to the actual page? Like on the black (or white, depending on your theme) space next to the page for now?

**Comment by DavidLazarescu** [comment]
I see, I suppose the arrow keys will be the only solution for now then. We will start working on the mobile version soon and I'll make sure to push the release improving touch asap.

**Comment by YosypC** [comment]
I remembered wrong, the non-document parts do not act as selection.

**Comment by DavidLazarescu** [comment]
Great then. As I said before, we will be working on better touch support when working on the mobile version of Librum.
