### ISSUE TITLE
Audiobooks?

### ISSUE THREAD

**Issue by fivestones** [Librum-Reader/Librum#69]
I'm just wondering if you have any plans to implement audiobooks. Your readme says `Librum is the best choice for all kinds of books, since Librum supports all major book formats...` but audiobooks aren't listed. Audiobook support is obviously a lot of additional work, but having it would be something probably a lot of people would love to use.

**Comment by DavidLazarescu** [comment]
Hey, we have audio books in mind and we really want to get support for that into Librum as well, but for now there still is a lot of work to be done on the e-book part of the app.

Once we got Librum to android, implemented tiers and statistics and some other smaller things, we will be looking into that :smile:

**Comment by tbabej** [comment]
Personally, I would argue that's already a crowded space (where even good OSS solutions exist, i.e. Jellyfin/Audiobookshelf). My two cents would be that the high-quality multi-device book reader is a real gap in the market, and Librum should really get good at that particular use case, before expanding to something as relatively complex as supporting audiobooks.

**Comment by fivestones** [comment]
> that's already a crowded space (where even good OSS solutions exist, i.e. Jellyfin/Audiobookshelf

But the space that is far from crowded is good quality book reader that can also do audiobooks. One of the few apps I’ve seen that does a really good job in my estimation is Libby, but as it’s only for library books and it’s sure not open source or self-hostable, it leaves a lot to be desired. I think Audiobookshelf is the one good contender as an open source solution for audiobooks, and is the only solution I know of that really can do both audiobooks and ebooks, but for ebooks the actual reading experience for ebooks is pretty bad. And Jellyfin, well, I love it in lots of ways but what do you use with it to actually listen to audiobooks? On iOS I haven’t found a good option. Besides the fact that it definitely isn’t made for ebooks.

So, yes, I agree with you that there is a lot of room for an app that does ebooks management and the reading experience really well. I’d love to see Librium do this well too. But I’m also excited to hear that it’s something the devs want to do.
