### ISSUE TITLE
translation software

### ISSUE THREAD

**Issue by fallsdevil** [Librum-Reader/Librum#70]
**Is your feature request related to a problem? Please describe.**
Not exactly, just an easy use for people who don't speak English as a second language or anything like that.

**Describe the solution you'd like**
A collaboration to translate the software into other languages.

**Describe alternatives you've considered**
Sites like Hosted Weblate or Crowdin would be great alternatives for this.

**Additional context**
It would be interesting if one of these languages ​​is Brazilian Portuguese so that I could help.

**Comment by DavidLazarescu** [comment]
I have started with translations for Librum yesterday, so we should have that done by the end of this week.

We currently have people for translating into: German, Russian, Italian and Mandarin.

It would be greatly appreciated if you help with portuguese.

**Comment by DavidLazarescu** [comment]
Hey @fallsdevil, I got the app set up for translations now and the German one is pretty much done, if you'd have some time and would still like to contribute to Librum, we could get started with the Portuguese translation.

**Comment by fallsdevil** [comment]
Of course, I would still like to contribute!

**Comment by DavidLazarescu** [comment]
> Of course, I would still like to contribute!

Great, do you by any chance have any experience with translating using Qt Linguist?

**Comment by fallsdevil** [comment]
No, I've been using Weblate and Crowdin for a short time

**Comment by DavidLazarescu** [comment]
Qt Linguist is very simple, once you download it you can open the file (https://gist.github.com/DavidLazarescu/92dd85187bf11ed69ab786c2c9c80551) and use Qt Linguist to translate the text from en to pt.

You can download linguist for windows on from here: https://github.com/thurask/Qt-Linguist. Else you can download Qt directly from here, which will also include Qt Linguist: https://www.qt.io/download-open-source.

Here is a short guide on how to use it: https://youtu.be/xNIz78IPBu0?t=347 (from min 5:47)

And of course, if you have any questions or run into any problems, feel free to reach out to me.

**Comment by DavidLazarescu** [comment]
Closing this issue since translation infrastructure was introduced in the latest release (v.0.10.2)

**Comment by sikmir** [comment]
Weblate would be a great option for translations.

**Comment by DavidLazarescu** [comment]
@sikmir looking into this right now!
