### ISSUE TITLE
Typo in CMakeLists breaks install process on linux

### ISSUE THREAD

**Issue by 3036662** [Librum-Reader/Librum#71]
Typo in CMakeLists breaks install process on linux
src/application/CMakeLists.txt

It looks like a simple typo.
After changing LINUX to UNIX, everything works
 ###### Install rules ######
-if(LINUX)
+if(UNIX)
     install(TARGETS application
             DESTINATION lib
             )

**Comment by DavidLazarescu** [comment]
Why would that break the install process on linux? `if(LINUX)` evaluates to true on linux

**Comment by 3036662** [comment]
Yes, it should. But i can't build with it, I'll check again.Thanks!

**Comment by 3036662** [comment]
I've found the root of problem. I was using cmake 3.23. And LINUX will normally evaluate only with 3.25 or higher.
It's more like compatibility question.
