### ISSUE TITLE
Copy text from pdf as plain text

### ISSUE THREAD

**Issue by g-kartik** [Librum-Reader/Librum#73]
**Is your feature request related to a problem? Please describe.**
When copying text from a PDF file, the formatting like carriage return also gets copied. This makes difficult to take notes by copying and pasting content from book.
Below is an example.
![super_gut](https://github.com/Librum-Reader/Librum/assets/83916067/085aa02c-03ae-4986-99a7-f1ba3853446d)

**Describe the solution you'd like**
We can strip off all kind of formatting including carriage return while copying. We can include option `copy as plain text` apart from the normal copy one.

**Describe alternatives you've considered**
The alternative would be manually strip off the formatting which is a tedious task

**Additional context**
None

**Comment by DavidLazarescu** [comment]
I could add an option to the settings that controls including new lines in copied text for the next release.

**Comment by g-kartik** [comment]
Thank you!

**Comment by DavidLazarescu** [comment]
This was implemented in the latest version (0.10.2)
