### ISSUE TITLE
Bookmark look-up words

### ISSUE THREAD

**Issue by g-kartik** [Librum-Reader/Librum#75]
**Is your feature request related to a problem? Please describe.**
The look-up feature is amazing and easy to use. However, we don't have any way to bookmark the words to build our own vocabulary.

**Describe the solution you'd like**
We can have a personal vocabulary system where one can bookmark the look-up words. Most of the times, we remember vocabulary from examples, so additionally, we can allow users to save the line where they are used as notes. If he revisits the same word, he can add more lines. This can also be saved to the cloud as user data.

**Describe alternatives you've considered**
Most dictionaries just allow us to save words and form a collection. However, most often we learn new words by their usage and context. Books are an excellent source which provide that context. None of the existing dictionary apps have such feature which is integrated into e-book readers. So I think this feature will be a game changer.

**Comment by DavidLazarescu** [comment]
That's a great idea, but it's quite specialised. I think you understand that our focus lies on adding more fundamental stuff before though.

We are of course happy to take PRs though, so if anyone wants to give this a shot, we'd be happy to work on this together.

**Comment by g-kartik** [comment]
Well, I feel motivated to work on a PR after reading your response. However I am a novice in the C++ language. Being well versed with python can you please suggest to me a book which is just enough to know the ins and outs of the language and quickly get started with contributing to Librum?

**Comment by DavidLazarescu** [comment]
Glad to hear that, c++ is great, especially in combination with Qt. I am a big fan of https://learncpp.com for starting with c++, so I'd recommend you that. After that you can look into Qt, it has great documentation and brings awesome abstractions to c++ which make your life much much easier.
