### ISSUE TITLE
Support folders

### ISSUE THREAD

**Issue by tbabej** [Librum-Reader/Librum#77]
With large collections of books, the interface of librum becomes more difficult to navigate. It would be helpful if users could organize their book collections into folders, and be able to navigate the folder tree to narrow down the book selection.

**Comment by tbabej** [comment]
I am talking about the navigation problems in particular, though I can see how folders would help with the performance too.

**Comment by DavidLazarescu** [comment]
I understand, have you looked at the tag system? It exists for pretty much exactly this purpose, to group books and it is already fully implemented.

**Comment by DavidLazarescu** [comment]
I have now started with an extensive support of folders to organize books, you can follow the progress in: https://github.com/Librum-Reader/Librum/tree/feat/shelves

**Comment by DavidLazarescu** [comment]
Just noticed that I didn't post an update on this, but as you might have noticed we have merged the feature into main and released it some versions ago.

Feel free to provide feedback on how you like it :smile:
