### ISSUE TITLE
M1 Mac Run Errors

### ISSUE THREAD

**Issue by mslmn** [Librum-Reader/Librum#85]
getting this error when I run the `librum` command

```
dyld[90104]: Library not loaded: build/shared-release/libmupdfcpp.so
  Referenced from: <01D222DF-B3FA-3BAC-9324-05AA1A0D1CD8> /usr/local/bin/librum
  Reason: tried: 'build/shared-release/libmupdfcpp.so' (no such file), '/System/Volumes/Preboot/Cryptexes/OSbuild/shared-release/libmupdfcpp.so' (no such file), 'build/shared-release/libmupdfcpp.so' (no such file)
[1]    90104 abort      librum
```

Tried following the instructions posted in #68 but no dice.

**Comment by DavidLazarescu** [comment]
Hey, did you run `sudo cmake --install .`? If so, is the libmupdfcpp.so file in `/usr/local`?

**Comment by DavidLazarescu** [comment]
If that file exists, the error probably happens due to the fact that MacOS does not automatically add `/usr/local/bin` and `/usr/local/lib` to `PATH`, so you'd manually need to do that to make sure that your system finds the binaries.

To do that, I think you will need to add both those paths to `/etc/paths`.

**Comment by DavidLazarescu** [comment]
Could you try adding it to `LD_LIBRARY_PATH` instead?

**Comment by Lmonster** [comment]
> Tried that, still getting the same error.
you can use` install_name_tool build/shared-release /path/to/libmupdfcpp.so librum` to change the rpath of the librum executable file

**Comment by DavidLazarescu** [comment]
Hey, try adding the folder to the DYLIB path variable as described here: https://github.com/Librum-Reader/Librum/issues/68#issuecomment-1877200951
