### ISSUE TITLE
Uninstalled. Requires an Account. Don't Install.

### ISSUE THREAD

**Issue by hp8wvvvgnj6asjm7** [Librum-Reader/Librum#95]
Why would I want to share my library info with you? Why do you want this information? Do you want to know what I'm reading? Gtfo

**Comment by arobase-che** [comment]
At first, I also thought it was a local only thing but no. It comes with a cloud substruction with free tier.

**Comment by DavidLazarescu** [comment]
> Why would I want to share my library info with you? Why do you want this information? Do you want to know what I'm reading? Gtfo

Because the whole reason behind Librum is online storage, automatic syncing across devices, user specific reading statistics, tools like AI explanations that need to be limited for each user and similar.

Librum is not just a local, offline file manager.

**Comment by DavidLazarescu** [comment]
> I got syncthing for that and its private.

You can self-host librum if you'd like to avoid sharing your data with a third party :smile:
