### ISSUE TITLE
[Feature Request] Support KOBO ebook devices 

### ISSUE THREAD

**Issue by pppaapp** [Librum-Reader/Librum#98]
[calibre-web](https://github.com/janeczku/calibre-web) has the ability to synchronize with kobo ebook devices

https://github.com/janeczku/calibre-web/wiki/Kobo-Integration

It would be nice if the Librum server also had the ability to synchronize with kobo ebook devices

**Comment by DavidLazarescu** [comment]
Thanks, we have added it onto our to-do list.
